### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tedsmith** [AmNe5iA/MKDecrypt#2]
Not an issue but wanted to say thanks for this work. It's fantastic. We met a year ago (perhaps you remember?) when you told me about this. I've been using it in various scenarios and was hoping to mention it at a "special" presentation next week in Europe. I've found it to work well with VC on Linux Mint. 

Really fantastic work. Thanks

**Comment by AmNe5iA** [comment]
Glad you like it.  I have been told it works on Kali too
