### ISSUE TITLE
Device Mapper

### ISSUE THREAD

**Issue by whoamins** [AmNe5iA/MKDecrypt#7]
![image](https://user-images.githubusercontent.com/66217512/135745648-b3711a50-58f6-455c-a920-d91601cad622.png)

**Comment by Byxs20** [comment]
Coincidentally, I'm also experiencing this problem, I'm using kali in vmware without this problem, I'm using ubuntu 20.04 with wsl2 with the same problem as you!


refer: https://github.com/microsoft/WSL/issues/8409

I solved the problem by manually creating a soft link myself, as shown here:

![image](https://github.com/AmNe5iA/MKDecrypt/assets/64669718/09dbccb2-ebbe-4be3-a67d-4e756730bc51)

I hope that helps! As a side note, if you reboot wsl, you have to go back to the soft link again to get it to work, which is kind of a pain in the ass!
